name: main

on:
  pull_request:
    branches:
      - ci

jobs:
  build-linux:
    runs-on: [self-hosted, 136787]
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v3
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
    - name: Test with pytest
      run: |
        pwd
        cd tmp
        pytest *
