name: main

on:
  pull_request:
    branches:
      - main

jobs:
  build-linux:
    runs-on: [self-hosted, intel]
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v3
    - name: Test with pytest
      run: |
        pwd
        cd ~/mll
        ls
