name: main

on:
  pull_request:
    branches:
      - main

jobs:
  unit-test:
    runs-on: [self-hosted, intel]
    container:
      image: intel/intel-extension-for-pytorch:latest
      ports:
        - 80


    steps:
    - uses: actions/checkout@v3
    - name: hello CI world
      run: |
        pwd
        cd ~/mll
        ls
    - name: Check container state
      run: |
        ldd --version
        xpu-smi
        python -c "import torch; print('torch:', torch.__version__, torch)"
        python -c "import torch; print('XPU available:', torch.xpu.is_available())"
