name: main

on:
  pull_request:
    branches:
      - main

jobs:
  unit-test:
    runs-on: [self-hosted, intel]
    container:
      image: intel/intel-extension-for-pytorch:2.1.20-xpu
      ports:
        - 80


    steps:
    - uses: actions/checkout@v3
    - name: hello CI world
      shell: bash
      run: |
        pwd
        ls
    - name: Check container state
      shell: bash
      run: |
        ldd --version
        python -c "import torch; print('torch:', torch.__version__, torch)"
        python -c "import torch; import intel_extension_for_pytorch; print('XPU available:', torch.xpu.is_available())"
